### ISSUE TITLE
JS are not managed

### ISSUE THREAD

**Issue by souro18** [UdacityFrontEndScholarship/task-master#100]
script are written in html files as of now. making separate js files for each page will make it more manageable .

**Comment by souro18** [comment]
want to work on it

**Comment by Rajrox97** [comment]
@souro18  yes. We would love it,  if you want to take it up . But we were experiencing some technical difficulties that we hope to iron out within 3/4 days. Then we will work on this issue. Meanwhile, i am keeping this issue open . 

Here are some guidelines that you must see. 

 To anyone who wants to work on this, here are a few notes.

We like the design. Do not change the design.
WRONG APPROACH: For example: You don't like the fonts, you change it?
CORRECT APPROACH: Our page is not being responsive, you fix it, with all the initial design, fonts,
and colors.

WRONG APPROACH: You want to add a feature, you just add it.
CORRECT APPROACH: You want to add a feature, you ask the moderators if they want that, host the
files in your github repo and submit github pages here in the comments below. After we review,
you can send a PR request, and we will definitely accept it. :) Cheers !!

**Comment by Rajrox97** [comment]
I also assigned you this task.Check it in 3/4 days. :)

**Comment by souro18** [comment]
Should I proceed now? @Rajrox97  @pbiswas101

**Comment by pbiswas101** [comment]
@souro18 yes you can!!
