### ISSUE TITLE
sign up page not responsive, also glitch problem at very beginning. 

### ISSUE THREAD

**Issue by sahkal** [UdacityFrontEndScholarship/task-master#104]

**Comment by Rajrox97** [comment]
To anyone who wants to work on this, here are a few notes.
1. We like the design. Do not change the design.
     WRONG APPROACH: For example: You don't like the fonts, you change it?
     CORRECT APPROACH: Our page is not being responsive, you fix it, with all the initial design, fonts, 
       and colors.


     WRONG APPROACH: You want to add a feature, you just add it.
     CORRECT APPROACH: You want to add a feature, you ask the moderators if they want that, host  the 
            files in your github repo and submit github pages here in the comments below. After we review, 
            you can send a PR request, and we will definitely accept it. :) Cheers !!

**Comment by creatorisback** [comment]
can we tweak things in design like i tried with signup form earlier ?
https://creatorisback.github.io/task-master/

**Comment by pbiswas101** [comment]
Don't tweak with the design!! If you can make it responsive just do that!
