### ISSUE TITLE
Fix the focussed Input

### ISSUE THREAD

**Issue by pbiswas101** [UdacityFrontEndScholarship/task-master#105]
When focussing on **input section** for _email_ or _password_ there are _lines_ on either side that appears which needs to be fixed!
![2018-04-16 2](https://user-images.githubusercontent.com/32795458/38795883-48ad1282-4177-11e8-9c64-3f16a9e931e7.png)
Fix those red lines on the side!
**NOTE** - these lines only appear when you click on the input section! _Do not alter or modify other aspects of the code while addressing this issue!_

**Comment by Adi-github** [comment]
![screenshot 41](https://user-images.githubusercontent.com/35623617/38797074-015cca4a-417b-11e8-8b8c-5c80e7eb8115.png)

it isnt showing up here

**Comment by Adi-github** [comment]
Oh Just checked and fixed it !!
it will be fixed with my latest pr

**Comment by bhaskarSingh** [comment]
@Adi-github  when can we expect the pull request?
