### ISSUE TITLE
Import framework rather using a cdn

### ISSUE THREAD

**Issue by creatorisback** [UdacityFrontEndScholarship/task-master#106]
I would suggest not to go with CDN as if we do have to change things we'are overwriting CSS every time and importing framework will give us the flexibility to tweak that.........I

**Comment by kadumuri1994** [comment]
Can I work on this issue?

**Comment by shashank-sharma** [comment]
Before we go ahead with this issue I just want to ask, Is it a good practice to change the CSS of materialize file rather than overwritting it ? If yes please provide one good explanation.

**Comment by creatorisback** [comment]
yes frameworks are there to help and make our tasks easy and customizing them can increase our productivity, let me explain with an example

Let's say we have a design system which has a certain type of inputs, buttons and navigation instead of overwriting your framework we'll customize itself in core files and now we can use elements everywhere without hesitating that design system would be violated by another team member(If he doesn't use our custom declared classes)

Moreover we are removing some dead code from framework

**Comment by shashank-sharma** [comment]
> customizing them can increase our productivity

There is also one term called maintainability, what if there is new version of materialize CSS available and now we want to shift all our CSS code to the new code base. How you are planning to solve this problem ? Because if we change the previous original css file to meet our condition then for this new css file we again might need to find all those elements and change each and every thing manually,

**Comment by creatorisback** [comment]
Upgrading framework is itself a tedious task I have been doing designing past 3 years and I've never done that do you think that just by replacing CDN files we could upgrade to next version? No ! we might have to change over the large scale to adapt according to that version

Design systems are kept solid, modular and customized for maintainability and using framework's compiled files violates all these...hope you would understand
