### ISSUE TITLE
hosting

### ISSUE THREAD

**Issue by Mayankjh** [UdacityFrontEndScholarship/task-master#11]
Can't we have this project hosted on github so that we can see the changes made live ?

**Comment by pbiswas101** [comment]
Yes, we will host this once we get the repository right!

**Comment by Mayankjh** [comment]
in the current repository it is mentioned that the work will be simultaneous on bootstrap and materialize will that be carried in the new repo or we shall stick to materialize

**Comment by pbiswas101** [comment]
No, it'll be Materialize, that's the reason we're changing the repo!

**Comment by Rajrox97** [comment]
No , Mayankjh, we cannot have a live version of this project untill and unless akshit sir creates one for us because we don't have settings access. :) Having said that, we have mailed him about this issue and it will be resolved soon. :)
