### ISSUE TITLE
Footer comes up with the keyboard when input field is selected on login & signup page

### ISSUE THREAD

**Issue by bhaskarSingh** [UdacityFrontEndScholarship/task-master#117]
![screenshot_20180419-211536](https://user-images.githubusercontent.com/16613455/39013352-c25a4478-4434-11e8-99f8-51cf77647e43.png)
![screenshot_20180419-211627](https://user-images.githubusercontent.com/16613455/39013353-c2ad451a-4434-11e8-995f-54312dd403f0.png)
The screenshot was taken from Lenovo-5inch-android os phone
also, the login& signup card is not exactly scrollable, the top part goes over the screen when an input field is selected & it's not scrollable
Whom so ever interested in this issue say so, wait for the moderator's permission then go ahead with resolving the issue

**Comment by bhaskarSingh** [comment]
make sure to try running the login & signup page on an actual device to get the idea of the issue

**Comment by Rajrox97** [comment]
Hi @bhaskarSingh  i have seen the issue. You can go ahead and work on this, as long as the design remains same.

**Comment by nsaicharan** [comment]
Can I work on this issue?

**Comment by pbiswas101** [comment]
@nsaicharan yes you can work on this issue but while fixing don't alter other principles e.g. responsiveness!
