### ISSUE TITLE
Modified tasks card

### ISSUE THREAD

**Issue by bhaskarSingh** [UdacityFrontEndScholarship/task-master#130]
Added shades of black according to task priority & scroll bar to task cards
link: https://bhaskarsingh.github.io/task-master/profile

**Comment by pbiswas101** [comment]
Great @bhaskarSingh it looks nice but I suggest if you can improve the UI a bit more then it would be awesome so as to include those major changes as well!

**Comment by bhaskarSingh** [comment]
What major changes?

**Comment by pbiswas101** [comment]
Major changes such as PR #133 ......if you can come up with some ideas?? @bhaskarSingh
