### ISSUE TITLE
The user dashboard page has some bug, seems not responsive.

### ISSUE THREAD

**Issue by RatnadeepBiswakarma** [UdacityFrontEndScholarship/task-master#134]
![responsive problem](https://user-images.githubusercontent.com/36644040/39185787-fbe8171a-47e5-11e8-8eb6-e7409585f7cc.PNG)

**Comment by souro18** [comment]
Just wondering if there is any device with that dimension

**Comment by shashank-sharma** [comment]
Hi @RatnadeepBiswakarma 
I am not able to generate this bug in my Chromium browser as well as Firefox. It is working fine. If possible can you please recheck and then send screenshot. We expect you to select "Responsive Site Mode" and then refresh the page. If then you will see the same error then let us know.

Also you can try to open this page from your Mobile. If in your mobile you see any bug then post your screenshot here.

What I found:

Chromiium:
![screenshot from 2018-04-24 23-03-26](https://user-images.githubusercontent.com/9320644/39203962-ffb4d292-4813-11e8-828e-0a48fcac281a.png)

Firefox:
![screenshot from 2018-04-24 23-02-35](https://user-images.githubusercontent.com/9320644/39203975-07ff88a2-4814-11e8-88bf-f39793df696c.png)

**Comment by RatnadeepBiswakarma** [comment]
Oh its ok after refreshing the page. Thanks @souro18 @shashank-sharma
