### ISSUE TITLE
Regarding mail us input on footer of index.html

### ISSUE THREAD

**Issue by ESHA1998** [UdacityFrontEndScholarship/task-master#135]
Hi! The input in the Mail Us section of footer is taken in black colour which reduces the visibility. This can be improved and would look better if made center-aligned. this would improve UI experience.
currently, it looks like this
![error](https://user-images.githubusercontent.com/30546596/39251536-2e716cfa-48c1-11e8-9e61-607b4924452b.png)
But it can be modified to-
![resolved](https://user-images.githubusercontent.com/30546596/39251557-3fedb308-48c1-11e8-87a0-a8e97910099c.png)
should I work upon it if required?

**Comment by pbiswas101** [comment]
@ESHA1998 yes you can work on it!!

**Comment by ESHA1998** [comment]
Changes committed!!

**Comment by pbiswas101** [comment]
@ESHA1998 provide a live link to your changes!

**Comment by ESHA1998** [comment]
yeah sure!!
https://ESHA1998.github.io/

**Comment by pbiswas101** [comment]
@ESHA1998 your repo is not up-to-date, sync it and then make a PR with all your commits squashed into one!

**Comment by ESHA1998** [comment]
oh! okay. will work on it

**Comment by Rajrox97** [comment]
Idle issue. Closing it.
