### ISSUE TITLE
Why Task Master section is not responsive

### ISSUE THREAD

**Issue by souro18** [UdacityFrontEndScholarship/task-master#136]
![image](https://user-images.githubusercontent.com/22174074/39254666-47355056-48c8-11e8-8a94-b3a3154f16e4.png)
Can I fix this?

**Comment by pbiswas101** [comment]
@souro18 currently another person is working on the responsiveness of **Why TaskMaster?**
But you can upload the video to your youtube channel and include it in _iframe_ tag! If it looks better we'll provide you with an official youtube channel for **TaskMaster**!

**Comment by souro18** [comment]
https://souro18.github.io/task-master/index.html
@pbiswas101 @Rajrox97

**Comment by Rajrox97** [comment]
@souro18  Aditya Sharma is working on the responsiveness of the why taskmaster section. Good job with the video. 

IT would be great if you could include the video on the left hand side and Align the "Introduction" heading above the paragraph. You will notice that the Introduction heading is currently center aligned.

**Comment by souro18** [comment]
You mean like this one?

![image](https://user-images.githubusercontent.com/22174074/39307399-53a8bd24-4980-11e8-821e-8481ea895183.png)

Or this one?
![image](https://user-images.githubusercontent.com/22174074/39307481-8a014968-4980-11e8-948f-5dc8c50977e3.png)
@Rajrox97

**Comment by Rajrox97** [comment]
hi @souro18  The first one would be great.
