### ISSUE TITLE
slider images are different for mobile view and laptop view.

### ISSUE THREAD

**Issue by souro18** [UdacityFrontEndScholarship/task-master#137]

**Comment by Rajrox97** [comment]
@souro18  Can you please elaborate a bit more on this issue?

**Comment by souro18** [comment]
Notice the slider images in laptop/desktop view(newly added by priyabrata ) and then switch to mobile view. You will notice that in mobile view the images are different(old one)

**Comment by i-shubhamprakash** [comment]
Hi @souro18 , Can you please provide some screenshots to clarify exactly what the issue is.

**Comment by Rajrox97** [comment]
@souro18 go ahead and make the mobile version like the desktop one.

**Comment by Rajrox97** [comment]
This issue is already resolved in an upcoming PR.
