### ISSUE TITLE
zoom the contents of navbar on hovering

### ISSUE THREAD

**Issue by ESHA1998** [UdacityFrontEndScholarship/task-master#140]
Hi! The contents in the navbar(home,introduction,why taskmaster and contact) can be increased in size when hovered upon to improve the UI experience.
eg-currently it looks like this upon hovering on introduction. 
![err2](https://user-images.githubusercontent.com/30546596/39303473-e5ce30ce-4973-11e8-8d23-3d871406cc7f.png)

it can be changed to
![res2](https://user-images.githubusercontent.com/30546596/39303493-01e2934a-4974-11e8-939a-7706286d6768.png)

Should i pull a request for this if required?

**Comment by Rajrox97** [comment]
I think we can do with the current UI . But,i am sure that there might be other issues which you may find suitable to work on.
