### ISSUE TITLE
Contact section input field "First Name" and submit button width.

### ISSUE THREAD

**Issue by i-shubhamprakash** [UdacityFrontEndScholarship/task-master#151]
1. A slight change in "**First Name**" to "**Your Name**" in the contact section. 
2. Submit button to too big, it might be a little less in width so that it looks better.

![taskmaster](https://user-images.githubusercontent.com/28767301/39424215-269122ac-4c93-11e8-9683-0ad6385bb6e4.png)
Should I work on this and change this?

**Comment by bhaskarSingh** [comment]
@i-shubhamprakash you can also give a little padding inside the edit boxes as its sticking to the left which doesn't look, just a suggestion.

**Comment by i-shubhamprakash** [comment]
Yes, it should have a little padding. I'll try to fix it.

**Comment by pbiswas101** [comment]
@sahkal is already working on the contact form!
It's great that you've raised the issue @i-shubhamprakash

**Comment by amarjeetsingh1999** [comment]
@shashank-sharma , @Rajrox97  i already fixed the issue of width of submit button in my PR #138 and it was also successfully accepted. Then how's it  that the size of button has again become inappropriately long?

**Comment by i-shubhamprakash** [comment]
@amarjeetsingh1999  I have attached an image there, you can see how it is looking now.
