### ISSUE TITLE
The Entire Landing page should be a One Page Template.

### ISSUE THREAD

**Issue by Rajrox97** [UdacityFrontEndScholarship/task-master#16]
If you don't know what is one page template, please google it :) 
Make sure all template uses Materialize and not Bootstrap. 

One page template will give the scrolling Feature.

Page 1:
![image](https://user-images.githubusercontent.com/25405869/38640856-16d37a9e-3df3-11e8-876d-720086582f43.png)

Since it is a one page template, when we scroll down, the introduction page slides downwards. :) 

Page 2: 
![image](https://user-images.githubusercontent.com/25405869/38640910-3cabdbc6-3df3-11e8-8fbb-a7febe9089d3.png)

Introduction should be on the same page . It should be a ONE PAGE TEMPLATE.
Text in introduction should preferably be the same.

Page 3: Within the first Page.
![image](https://user-images.githubusercontent.com/25405869/38641027-94d44bbc-3df3-11e8-82b9-7470cfce4a51.png)

The Footer 
![image](https://user-images.githubusercontent.com/25405869/38641113-ce56347c-3df3-11e8-9c6b-24df073314e8.png)

The footer should contain the Contact me form where the Contact me form slides into the page.

**Comment by phanindrakoka09** [comment]
actually to address this issue we need to code in css  and it will give the desired output! do you want me to work on that !
