### ISSUE TITLE
Hover Effect on Social Media links and other links on the footer.

### ISSUE THREAD

**Issue by utkarsh2102** [UdacityFrontEndScholarship/task-master#169]
It'd be to nice to have a hover effect on the social media links and the other things on the footer.
Plus, we can have a darker hover effect on the buttons. It'd look better that way.
Let me know if you consider this, I'll make a PR for the same. 
CC : @pbiswas101 @Rajrox97 @sahkal and other mods and co-mods.

**Comment by utkarsh2102** [comment]
Got confirmation from @pbiswas101. I'm working on the same.

**Comment by Rajrox97** [comment]
@utkarsh2102  Don't change effect on the buttons.  You can add hover effect on social media links.

**Comment by utkarsh2102** [comment]
As you say @Rajrox97.
But the hover effect on the buttons on the footer isn't really visible. I can just change the opacity or the z-index to make it visible. Let me know if I should or not :)
