### ISSUE TITLE
No Validation and No Emailing Feature

### ISSUE THREAD

**Issue by sumilmehta** [UdacityFrontEndScholarship/task-master#171]
There is no validation in the in feedback form. Also, I added a little php code for email functionality.
I tried to send a pull request but was denied access. I am attaching the files here

[New folder.zip](https://github.com/UdacityFrontEndScholarship/task-master/files/1977156/New.folder.zip)

**Comment by Rajrox97** [comment]
PR's(except those which are already assigned) will not be accepted.
