### ISSUE TITLE
Navbar at the top and Footer subscription form styling

### ISSUE THREAD

**Issue by mmnauman** [UdacityFrontEndScholarship/task-master#174]
The background of the Navbar should be transparent as it is not standing out with slider. 

Please add a the placeholder text like **Enter Your Email** and the Font-text also is black and the background also is dark so please change it to white.
![mail us](https://user-images.githubusercontent.com/23205151/39753452-77ee40e0-52dc-11e8-91be-066e0e5a2505.PNG)

Footer background is not appealing.

**Comment by nehavatsyan** [comment]
Is this issue assigned to someone ? if not can i work on it

**Comment by pbiswas101** [comment]
Yes @mmnauman we're getting rid of the mail us section as that seems redundant given that we do have a **Contact** section!
This removal will be addressed by Aditya in his next PR!
So, there is no question of placeholder!!
