### ISSUE TITLE
favicon icon for the website

### ISSUE THREAD

**Issue by vattytrivedi** [UdacityFrontEndScholarship/task-master#178]

**Comment by Rajrox97** [comment]
Please provide what icon you want to upload as a favicon?

**Comment by vattytrivedi** [comment]
Favicons:

![taskmaster-1](https://user-images.githubusercontent.com/14287645/39954268-338673e0-55da-11e8-8af8-41ee70554d06.jpg)
![taskmaster-2](https://user-images.githubusercontent.com/14287645/39954269-34016e38-55da-11e8-838f-e2d30c38a22b.png)
![taskmaster-3](https://user-images.githubusercontent.com/14287645/39954270-344b1416-55da-11e8-855f-931a30e5b593.png)

**Comment by Rajrox97** [comment]
Nah I think we can do without a favicon at the moment.
