### ISSUE TITLE
(minor error) improper placing of phone ui image 

### ISSUE THREAD

**Issue by sskanishk** [UdacityFrontEndScholarship/task-master#179]
![screen shot 2018-05-11 at 8 32 06 pm](https://user-images.githubusercontent.com/29313203/39931250-75f12552-555a-11e8-905e-9dc67c64fc29.png)

Can I work on it?

**Comment by Rajrox97** [comment]
i have noticed this when we go to desktop view in a mobile phone. But never have i seen it from a mobile itself. Can you send a ss from your mobile?

**Comment by sskanishk** [comment]
@Rajrox97 
### yup its good in mobile, but in Chrome DevTool having same problem
.
.

![whatsapp image 2018-05-12 at 8 04 53 pm](https://user-images.githubusercontent.com/29313203/39958419-228e6700-5620-11e8-8938-5ee5b2cbdbc4.jpeg)


![screen shot 2018-05-12 at 8 09 28 pm](https://user-images.githubusercontent.com/29313203/39958435-667fefba-5620-11e8-9628-306cb914b337.png)
