### ISSUE TITLE
why you are using two versions of css 

### ISSUE THREAD

**Issue by abulhayat1** [UdacityFrontEndScholarship/task-master#18]
we should remove the minified version, it will be easy to work with the normal version

**Comment by Rajrox97** [comment]
Hi abhulhayat , we do not edit the pages in minified CSS. Its the normal version we work with. Minified is used to lessen loading times of the website.

HAving said that, you don't have to worry about the minified css.

Make changes in the normal CSS version only.Here is a link to address your doubts. :)

https://www.hanselman.com/blog/TheImportanceAndEaseOfMinifyingYourCSSAndJavaScriptAndOptimizingPNGsForYourBlogOrWebsite.aspx

Let me know if you have any more question , or if i may close this issue.
