### ISSUE TITLE
Unresponsive welcome page and text overflowing

### ISSUE THREAD

**Issue by sanchit0496** [UdacityFrontEndScholarship/task-master#189]
The welcome page is quite unresponsive on mobile devices. Also, padding and margin can be used in a better way. This will give a professional touch to the welcome page. 

I've made some similar sort of page before. Have a look here https://github.com/sanchit0496/FrontEnd_Projects/tree/master/LandingPage01

If the moderators approve, I'll commit the necessary modifications

**Comment by ribasu97** [comment]
Heey @sanchit0496 Sanchit! :) Please attach screenshots of the mentioned issues first. :)

**Comment by sanchit0496** [comment]
![gi1](https://user-images.githubusercontent.com/32457437/41275221-cc69c136-6e3d-11e8-92dc-8ed7dbfb3381.JPG)
![gi2](https://user-images.githubusercontent.com/32457437/41275223-ccd9bb08-6e3d-11e8-8237-a178c9f9ed52.JPG)
![gi3](https://user-images.githubusercontent.com/32457437/41275225-cd1bb2c4-6e3d-11e8-837f-61806dc9550b.JPG)
![gi4](https://user-images.githubusercontent.com/32457437/41275227-cd5f7ab8-6e3d-11e8-9e3e-9bb92dde743a.JPG)

Also, the contact form takes a lot of screen height and the div below it needs some extra padding and increased font size and font weight to look better. Several modifications could be done to improve the UI/UX of the main page.

**Comment by ribasu97** [comment]
Yes, i figured. Thing is , we didn't follow the design principles of "Designing from small to large" as it is given in the nanodegree . The contributors and moderators just checked it on their devices and it seemed to be okay. So i think since we are not planning to revamp the project, i will just let it pass.
