### ISSUE TITLE
Add a wallpaper that changes with time. 

### ISSUE THREAD

**Issue by Rajrox97** [UdacityFrontEndScholarship/task-master#19]
Can anyone add a wallpaper that changes with time? 

At t=x sec
![image](https://user-images.githubusercontent.com/25405869/38641805-b72d8956-3df5-11e8-91d9-e88afdc2636d.png)

At t=x+3 sec
![image](https://user-images.githubusercontent.com/25405869/38641854-d5a571e6-3df5-11e8-83f2-33b898a7fdde.png)

At t=6 seconds
![image](https://user-images.githubusercontent.com/25405869/38641898-f0a634d0-3df5-11e8-9f69-60da5bbd76b3.png)

**Comment by user501254** [comment]
That cannot be done with just a single conventional wallpaper. You would need multiple wallpapers and change them using CSS transition effects or using JavaScript.

**Comment by Rajrox97** [comment]
Hi @user501254  

I understand that :) In the image folders, you will see there are three basic wallpapers just for this. :)
