### ISSUE TITLE
Sliding images fit to fullscreen

### ISSUE THREAD

**Issue by pbiswas101** [UdacityFrontEndScholarship/task-master#20]
Make the sliding image of full viewport width and height without compromising the next sections & also add a button as shown - 
![2018-04-12](https://user-images.githubusercontent.com/32795458/38644680-f5c49d9a-3dfe-11e8-9a5f-6ec555380394.png)

**Comment by yashsartanpara** [comment]
In the recent merge,  i am not able to click on down arrow.
