### ISSUE TITLE
Need modification in Homepage | Mobile Compatible

### ISSUE THREAD

**Issue by shashank-sharma** [UdacityFrontEndScholarship/task-master#31]
For mobile view it is not looking great. We need to fix this.
If anyone want to work on this please make sure you comment here that you are working on it.

![screenshot from 2018-04-12 18-59-39](https://user-images.githubusercontent.com/9320644/38680379-d073e9c6-3e83-11e8-9352-1ab0281f11c9.png)

**Comment by nsaicharan** [comment]
Can I work on this issue?

**Comment by nsaicharan** [comment]
I've made slider section of the homepage mobile compatible, but I'm not sure if it's still valid now. Am I too late?

Video - https://app.hyfy.io/v/abaLGbsH3Tn/

![tasker2 surge sh_ iphone 6_7_8 plus](https://user-images.githubusercontent.com/17238374/38698248-1377147c-3eb2-11e8-9a7b-2b0bb76cf30d.png)


![homepage3](https://user-images.githubusercontent.com/17238374/38698141-ab423fc6-3eb1-11e8-97e7-732a991dd156.png)

**Comment by pbiswas101** [comment]
Try to implement these design on the updated repo @nsaicharan

**Comment by shashank-sharma** [comment]
@pbiswas101 As mentioned earlier, it is important that the PR reference this issue. Then only close any issue. Just a good practice which needs to be followed and you need to take care that others do that too.
