### ISSUE TITLE
Navigation bar drop down should appear when we resize the page. 

### ISSUE THREAD

**Issue by Rajrox97** [UdacityFrontEndScholarship/task-master#33]
![image](https://user-images.githubusercontent.com/25405869/38684487-6f0b1e16-3e8d-11e8-8810-0474d2fdc1c1.png)

**Comment by souro18** [comment]
would like to work on this

**Comment by souro18** [comment]
will sidenav work for this?or it has to be a dropdown?

**Comment by pbiswas101** [comment]
@souro18 please go for side nav if possible 'cause it would be easier in _Materialize_!
