### ISSUE TITLE
Adding Social Media Icons.

### ISSUE THREAD

**Issue by Rajrox97** [UdacityFrontEndScholarship/task-master#35]
![image](https://user-images.githubusercontent.com/25405869/38685537-cd7b2f3e-3e8f-11e8-95f8-2bece981bb7c.png)

Either ADD icons of the social media in the footer, **OR** add  social media SIDEBAR.

**Comment by Rajrox97** [comment]
Go Ahead. :+1:

**Comment by Adi-github** [comment]
added already please check my latest pull request

**Comment by yashsartanpara** [comment]
Current footer looks pretty broke in my system

**Comment by souro18** [comment]
yes ..same to me..and footer icons were added without a sync with master repo. please request everyone to up-to-date their repo before making a pull request . someone made one pull request without updating his repo and my contribution is deleted now.this is so not expected in git. @pbiswas101 @Rajrox97 please look into this matter.
