### ISSUE TITLE
Modification in Login Page | Mobile Compatible

### ISSUE THREAD

**Issue by shashank-sharma** [UdacityFrontEndScholarship/task-master#65]
For some reason the login page div is overflowing and overlapping the footer. This needs to be fixed and also it must look nice in Mobile view. (Can be seen in Screenshot)

If you are new to Github and want to take on this issue then please do comment down and start working.

![screenshot from 2018-04-13 22-50-12](https://user-images.githubusercontent.com/9320644/38748918-6b4ce742-3f6d-11e8-9881-595e953e6c8c.png)

**Comment by bhaskarSingh** [comment]
oh, i think that's my doing , i removed the container class to fix the bug relating to #62 it was working fine on the browers, didn't checked for the mobile sorry guys

**Comment by AsthaKhurana** [comment]
@bhaskarSingh you can fix it then !

**Comment by bhaskarSingh** [comment]
ok i will

**Comment by shashank-sharma** [comment]
@bhaskarSingh @AsthaKhurana  Your PR was merged at 11:07 PM and this issue was opened at 10:53

So it's not your mistake, it's the bug which is originally generated by the creator of this page, So you can try to focus on real issue :D

**Comment by bhaskarSingh** [comment]
I have resolved the issue.
