### ISSUE TITLE
Modification in Loading animation

### ISSUE THREAD

**Issue by shashank-sharma** [UdacityFrontEndScholarship/task-master#84]
It would be great if anyone can come up with better implementation to view loading div. (Can be seen in screenshot)
Currently if you will refresh, then you will notice one loading animation but it's looking great.

We can try to put whole background as white when the page is loading and then show the content.

![screenshot from 2018-04-14 17-56-01](https://user-images.githubusercontent.com/9320644/38768225-ade8562c-400d-11e8-8afa-ca6b62e1d3fa.png)

**Comment by Adi-github** [comment]
it's been implemented by me
I am on it already will enhance it to meet the request 
don't assign it to others as it will be just 
waste to time for us

**Comment by shashank-sharma** [comment]
@Adi-github  No problem, sure go ahead
