### ISSUE TITLE
Homepage Slider UI should be better and scroll should be smooth

### ISSUE THREAD

**Issue by creatorisback** [UdacityFrontEndScholarship/task-master#92]
There is a pending pull request from a user who has done tweaking on sliders issue no. #70 
please merge so I can take a pull and fix this up

**Comment by Rajrox97** [comment]
Hi @creatorisback  we are currently closing this issue. But we have developed some technical problems and are making the site a bit stable at first. :) 

Meanwhile, here are a few guidelines(also updated in the readme)

Suppose we want our page to be responsive. What does it mean?

We like the design. Do not change the design.
WRONG APPROACH: For example: You don't like the fonts, you change it?
CORRECT APPROACH: Our page is not being responsive, you fix it, with all the initial design, fonts,
and colors.

WRONG APPROACH: You want to add a feature, you just add it.
CORRECT APPROACH: You want to add a feature, you ask the moderators if they want that, host the
files in your github repo and submit github pages here in the comments below. After we review,
you can send a PR request, and we will definitely accept it. :) Cheers !!
