### ISSUE TITLE
No introduction section in index and navbar not responsive

### ISSUE THREAD

**Issue by souro18** [UdacityFrontEndScholarship/task-master#94]
![image](https://user-images.githubusercontent.com/22174074/38771019-42cc658c-4039-11e8-92c6-33ad521fe012.png)
also slider image is changing too fast

**Comment by creatorisback** [comment]
Issue was fixed in pull request #91

**Comment by Rajrox97** [comment]
@creatorisback  no it was not. I am now sitting here trying to revert PR 87. :)

**Comment by creatorisback** [comment]
![capture](https://user-images.githubusercontent.com/28557067/38771417-beb26802-4040-11e8-8a40-68db2e781f96.PNG)


Please visit https://creatorisback.github.io/task-master/

**Comment by creatorisback** [comment]
@Rajrox97 I think nothing was wrong with #87 as it is working fine on forked repo.......if you do find an issue please let me know.

**Comment by Rajrox97** [comment]
@creatorisback we were experiencing some bugs in the home page after issue 86 onwards. :) i guess it was from 87 to the later issues. We wanted to be sure that everything was fine so reverted back to the last stable version . This issue we will work in some days . :)  You can fix it then. Meanwhile here are some guidelines. 


To anyone who wants to work on this, here are a few notes.

We like the design. Do not change the design.
WRONG APPROACH: For example: You don't like the fonts, you change it?
CORRECT APPROACH: Our page is not being responsive, you fix it, with all the initial design, fonts,
and colors.

WRONG APPROACH: You want to add a feature, you just add it.
CORRECT APPROACH: You want to add a feature, you ask the moderators if they want that, host the
files in your github repo and submit github pages here in the comments below. After we review,
you can send a PR request, and we will definitely accept it. :) Cheers !!
